[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/submissions"
  to = "/.netlify/functions/submissions"
  status = 200
  force = true

[[redirects]]
  from = "/api/media"
  to = "/.netlify/functions/media"
  status = 200
  force = true

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200
  force = true
